#!/bin/sh
### BEGIN INIT INFO
# Provides:             ebusd
# Required-Start:       $networking
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    Automatic startup script for the eBUSd

PATH=/sbin:/bin:/usr/bin:/usr/sbin
. /etc/init.d/functions

export PUREGEV_ROOT=/usr/lib/ebus
export LD_LIBRARY_PATH=$PUREGEV_ROOT

DESCRIPTION="eBUS SDK Daemon"
NAME="eBUSd"
DAEMON="/usr/bin/ebus/eBUSd"
PIDFILE="/var/run/eBUSd.pid"

#
# Function that starts the daemon/service
#
startdaemon()
{
	start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null 	|| return 1
	start-stop-daemon --start --quiet --exec $DAEMON -- --pidfile=$PIDFILE || return 2
}

#
# Function that stops the daemon/service
#
stopdaemon()
{
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
	[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
	startdaemon

        ;;
  stop)
        stopdaemon
        ;;

  restart)
	stopdaemon
	startdaemon
	;;
esac

exit 0
