#!/bin/sh
### BEGIN INIT INFO
# Provides:             i3ds-startup
# Required-Start:       $networking
# Required-Stop:        
# Default-Start:        2 3 4 5
# Default-Stop:         1
# Short-Description:    Automatic startup script for I3DS

PATH=/sbin:/bin:/usr/bin:/usr/sbin:/usr/local/bin
. /etc/init.d/functions

function startprog() {
	 prog=$1
	 logname=$2
	 if [ -z "$logname" ]; then
	    logname=/dev/null
	 fi
	 logdir=/var/log/i3ds
	 logfile="${logdir}/${logname}"

	 echo "Starting $prog"
	 echo "Logging to $logfile"

	 mkdir -p "${logdir}"
	 nohup /usr/bin/restarting.sh $prog > $logfile 2>&1 &
	 
}

function killprog() {
	 name=$1

	 pid=$(ps x | grep run | grep restarting | grep $name | grep -v grep | head -n1 | awk '{ print $1 }')
	 echo "Killing PID: $pid"
	 kill $pid
	 if [ $? -ne 0 ]; then
	     echo "Could not kill $name restarter"
	 fi

	 /bin/usleep 1000
	 pid=$(ps x | grep i3ds | grep -v restarting | grep $name | grep -v grep | head -n1 | awk '{ print $1 }')
	 echo "Killing PID: $pid"
	 kill $pid
	 if [ $? -ne 0 ]; then
	     echo "Could not kill $name app"
	 fi
}

function startdaemon() {
         echo "Switching power on"
         i2cset -y 2 0x22 0x8C 0x00
	 i2cset -y 2 0x22 0x04 0xFF

	 #echo "Waiting for cameras to start"
	 #sleep 10

         echo "Starting I3DS nodes"    
	 chmod +x /usr/bin/i3ds_cosine_*
	 startprog "run_address_server" address_server
	 startprog "run_sintef_flash" flash
	 startprog "run_power_control" power_control
	 startprog "run_trigger" trigger
	 startprog "run_cosine_tir" cosine_tir
	 startprog "run_basler_hr" basler_hr
	 startprog "run_cosine_stereo" cosine_stereo
	 startprog "run_analog_tactile" analog_tactile
	 startprog "run_analog_ft" analog_ft
	 startprog "run_analog_thermistor" analog_thermistor
	 startprog "run_cosine_hr" cosine_hr
	 echo "Done."
}

function stopdaemon(){
	 echo "Stopping I3DS nodes"
	 killprog i3ds_address_server
	 killprog i3ds_power_control
	 killprog i3ds_trigger
	 killprog tir
	 pid=$(ps x | grep i3ds_cosine_camera | grep tir | awk '{ printf $1 }')
	 kill $pid
	 killprog i3ds_basler_hr
	 killprog stereo
	 pid=$(ps x | grep i3ds_cosine_camera | grep stereo | awk '{ printf $1 }')
	 kill $pid
	 killprog tactile
	 killprog piap_analog
	 killprog thermistor
	 killprog hr
	 pid=$(ps x | grep i3ds_cosine_camera | grep hr | awk '{ printf $1 }')
	 kill $pid
	 echo "Done."
}

case "$1" in
  start)
	startdaemon        
        
        ;;
  stop)
        stopdaemon
        ;;

  restart)
	stopdaemon
	startdaemon
	;;
esac

exit 0
