#! /bin/sh

exec i3ds_cosine_hr \
     --node 312 \
     --camera-name i3ds-highres
     --trigger 1 \
     --trigger-node 300 \
     --trigger-camera-output 5 \
     --trigger-camera-offset 5000 \
     --flash 1 \
     --flash-node 298 \
     --trigger-flash-output 8 \
     --trigger-flash-offset 4950 \
     --pattern 1 \
     --trigger-pattern-output 6 \
     --trigger-pattern-offset 0
